package eu.kanade.tachiyomi.animeextension.zh.hanime1

object Tags {
    val CATEGORY_TRANSLATIONS = mapOf(
        "人物關係" to "Character Relationships",
        "外貌身材" to "Appearance and figure",
        "影片屬性" to "Video Properties",
        "性交體位" to "Sex positions",
        "情境場所" to "situational place",
        "故事劇情" to "story plot",
        "角色設定" to "Character setting",
    )
    val TAG_TRANSLATIONS = mapOf(
        "1080p" to "1080p",
        "3P" to "3P",
        "60FPS" to "60FPS",
        "69" to "69",
        "AI解碼" to "AI decoding",
        "ASMR" to "ASMR",
        "BDSM" to "BDSM",
        "JK" to "JK",
        "NTR" to "NTR",
        "OL" to "OL",
        "POV" to "POV",
        "一字馬" to "One word horse",
        "丁字褲" to "Thong",
        "不良少女" to "bad girl",
        "世界末日" to "the end of the world",
        "中文字幕" to "Chinese subtitles",
        "中文配音" to "Chinese dubbing",
        "丸子頭" to "Meatball head",
        "乳交" to "Titty Fuck",
        "乳牛" to "cow",
        "乳環" to "breast ring",
        "乳頭交" to "nipple sex",
        "人妻" to "wife",
        "保健室" to "Health Room",
        "修女" to "Nun",
        "健身房" to "gym",
        "偶像" to "idol",
        "偽娘" to "pseudo-girl",
        "傲嬌" to "Tsundere",
        "兔女郎" to "Bunny Girl",
        "內射" to "Creampie",
        "公主" to "Princess",
        "公共廁所" to "public restroom",
        "公眾場合" to "public place",
        "凌辱" to "Insult",
        "出軌" to "cheating",
        "刺青" to "tattoo",
        "十指緊扣" to "Fingers clasped together",
        "口交" to "Blowjob",
        "口爆" to "Blowjob",
        "口罩" to "mask",
        "古裝" to "costume",
        "吊襪帶" to "garter",
        "同事" to "colleague",
        "同人作品" to "Fan Works",
        "吞精" to "swallowing semen",
        "吸血鬼" to "Vampire",
        "和服" to "kimono",
        "哥布林" to "Goblin",
        "哥德" to "goth",
        "啦啦隊" to "cheerleading",
        "噴奶" to "squirting milk",
        "圍裙" to "apron",
        "圖書館" to "library",
        "外射" to "Outside Shot",
        "夜店" to "nightclub",
        "大小姐" to "Miss",
        "大屌" to "big dick",
        "天使" to "angel",
        "女僕" to "maid",
        "女兒" to "daughter",
        "女忍者" to "Female Ninja",
        "女戰士" to "Female Warrior",
        "女教師" to "female teacher",
        "女王樣" to "Queen-like",
        "女病人" to "female patient",
        "女警" to "Policewoman",
        "女醫生" to "female doctor",
        "女騎士" to "Female Knight",
        "女鬼" to "Female Ghost",
        "妖精" to "goblin",
        "妹" to "Sister",
        "姐" to "Sister",
        "姐妹丼" to "Sisters Don",
        "婚紗" to "wedding dress",
        "尋歡洞" to "Gloryhole",
        "尖耳朵" to "pointy ears",
        "巨乳" to "big breasts",
        "巫女" to "Witch",
        "師生" to "teachers and students",
        "強制" to "force",
        "後宮" to "harem",
        "御姐" to "royal sister",
        "性奴隸" to "sex slave",
        "性感內衣" to "Sexy lingerie",
        "性暴力" to "sexual violence",
        "性玩具" to "sex toys",
        "性轉換" to "sexual conversion",
        "怪獸" to "monster",
        "情侶" to "couple",
        "愛情賓館" to "Love Hotel",
        "懷孕" to "pregnancy",
        "戀愛喜劇" to "romance comedy",
        "戶外野戰" to "Outdoor Battle",
        "手交" to "Handjob",
        "打屁股" to "spanking",
        "扯頭髮" to "hair pulling",
        "扶他" to "help him",
        "拳交" to "fisting",
        "指交" to "finger intercourse",
        "掐脖子" to "Choke the neck",
        "排便" to "defecation",
        "接吻" to "kiss",
        "攝影" to "Photography",
        "放尿" to "pee",
        "教堂" to "church",
        "教室" to "classroom",
        "斷面圖" to "section view",
        "旗袍" to "cheongsam",
        "時間停止" to "time stops",
        "曬痕" to "sun marks",
        "校園" to "campus",
        "榨精" to "Extract the essence",
        "機械姦" to "Mechanical Rape",
        "機械娘" to "Machine Girl",
        "正太" to "shota",
        "死庫水" to "Dead reservoir water",
        "母" to "mother",
        "母女丼" to "Mother and daughter donburi",
        "毒龍鑽" to "Poison Dragon Diamond",
        "比基尼" to "bikini",
        "水手服" to "sailor suit",
        "沙灘" to "beach",
        "泳裝" to "swimsuit",
        "浴室" to "bathroom",
        "淫紋" to "obscene lines",
        "深喉嚨" to "deep throat",
        "游泳池" to "swimming pool",
        "溫泉" to "hot spring",
        "潮吹" to "squirting",
        "火車便當" to "train lunch",
        "無口" to "no mouth",
        "無碼" to "Uncoded",
        "無表情" to "expressionless",
        "熟女" to "Mature woman",
        "熱褲" to "hot pants",
        "獵奇" to "curious",
        "獸交" to "bestiality",
        "獸娘" to "beast mother",
        "獸耳" to "animal ears",
        "男乳首責" to "The first responsibility for male breasts",
        "男教師" to "male teacher",
        "異世界" to "different world",
        "異物插入" to "foreign object insertion",
        "異種族" to "different race",
        "異色瞳" to "Heterochromatic pupils",
        "病嬌" to "Yandere",
        "痴女" to "slut",
        "痴漢" to "Crazy man",
        "白虎" to "White Tiger",
        "百合" to "Lily",
        "監獄" to "prison",
        "眼神死" to "dead eyes",
        "眼罩" to "eye patch",
        "眼鏡娘" to "Glasses",
        "睡眠姦" to "Sleep rape",
        "睡衣" to "pajamas",
        "短髮" to "short hair",
        "碧池" to "Bichi",
        "窗邊" to "windowside",
        "精神崩潰" to "mental breakdown",
        "精神控制" to "mind control",
        "純愛" to "Pure Love",
        "素股" to "Sugu",
        "絲襪" to "Stockings",
        "綑綁" to "bundle",
        "緊身衣" to "tights",
        "美人痣" to "Beauty mark",
        "群交" to "Group sex",
        "耽美" to "Danmei",
        "肉便器" to "meat toilet",
        "肉棒打臉" to "cock slap in the face",
        "肌肉女" to "Muscular Girl",
        "肛交" to "anal sex",
        "胃凸" to "stomach protrusion",
        "背後位" to "back bit",
        "腋交" to "axillary sex",
        "腋毛" to "armpit hair",
        "腳交" to "footjob",
        "自慰" to "masturbation",
        "舌吻" to "tongue kiss",
        "舌環" to "tongue ring",
        "舔穴" to "licking pussy",
        "舔耳朵" to "lick ears",
        "舔腋下" to "Lick armpit",
        "舔腳" to "licking feet",
        "舔蛋蛋" to "lick balls",
        "著衣" to "clothing",
        "藥物" to "drug",
        "處女" to "virgin",
        "蟲姦" to "insect rape",
        "觸手" to "tentacle",
        "調教" to "training",
        "護士" to "nurse",
        "貧乳" to "Small breasts",
        "跳蛋" to "vibrating egg",
        "身體寫字" to "body writing",
        "車震" to "car shock",
        "輪姦" to "gang rape",
        "辦公室" to "office",
        "近親" to "close relative",
        "迷你裙" to "miniskirt",
        "逆強制" to "Reverse coercion",
        "遊艇" to "yacht",
        "醉酒" to "drunk",
        "醫院" to "hospital",
        "開大車" to "Drive a big car",
        "阿嘿顏" to "Aheyan",
        "陰毛" to "pubic hair",
        "陰道外翻" to "Vaginal eversion",
        "雌小鬼" to "Female Imp",
        "雙洞齊下" to "Both holes go down together",
        "雙馬尾" to "Twin Ponytails",
        "電影院" to "cinema",
        "電車" to "Tram",
        "露營帳篷" to "camping tent",
        "青梅竹馬" to "childhood sweetheart",
        "項圈" to "collar",
        "頸手枷" to "fail",
        "顏射" to "Facial",
        "顏面騎乘" to "face riding",
        "風俗娘" to "Custom Girl",
        "飛機杯" to "airplane cup",
        "馬尾" to "horsetail",
        "騎乘位" to "riding position",
        "體操服" to "gym uniform",
        "高跟鞋" to "high heels",
        "髮交" to "hand over",
        "魅魔" to "Succubus",
        "魔女" to "Witch",
        "魔法少女" to "Magical Girl",
        "魔物娘" to "Monster Girl",
        "黑皮膚" to "dark skin",
    )
    val GENRE_TRANSLATIONS = mapOf(
        "全部" to "all",
        "裏番" to "Rifan",
        "泡麵番" to "Instant Noodles",
        "Motion Anime" to "Motion Anime",
        "3DCG" to "3DCG",
        "2.5D" to "2.5D",
        "2D動畫" to "2D animation",
        "AI生成" to "AI generated",
        "MMD" to "MMD",
        "Cosplay" to "Cosplay",
    )
    val SORT_TRANSLATIONS = mapOf(
        "最新上市" to "Newest",
        "最新上傳" to "Latest Upload",
        "本日排行" to "Today's Ranking",
        "本週排行" to "Weekly Ranking",
        "本月排行" to "Monthly Ranking",
        "觀看次數" to "Most Views",
        "讚好比例" to "Highest Rating",
        "時長最長" to "Longest Duration",
        "他們在看" to "Popular Now",
    )
    val YEAR_TRANSLATIONS = mapOf(
        "全部年份" to "All Years",
    )
    val MONTH_TRANSLATIONS = mapOf(
        "全部月份" to "All Months",
    )
    fun getOriginalCategory(englishCategory: String): String? {
        return CATEGORY_TRANSLATIONS.entries.find { it.value.equals(englishCategory, ignoreCase = true) }?.key
    }
    fun getOriginalTag(englishTag: String): String? {
        return TAG_TRANSLATIONS.entries.find { it.value.equals(englishTag, ignoreCase = true) }?.key
    }
    fun getOriginalGenre(englishGenre: String): String? {
        return GENRE_TRANSLATIONS.entries.find { it.value.equals(englishGenre, ignoreCase = true) }?.key
    }
    fun getOriginalSort(englishSort: String): String? {
        return SORT_TRANSLATIONS.entries.find { it.value.equals(englishSort, ignoreCase = true) }?.key
    }
    fun getOriginalYear(englishYear: String): String? {
        return YEAR_TRANSLATIONS.entries.find { it.value.equals(englishYear, ignoreCase = true) }?.key ?: englishYear
    }
    fun getOriginalMonth(englishMonth: String): String? {
        return MONTH_TRANSLATIONS.entries.find { it.value.equals(englishMonth, ignoreCase = true) }?.key ?: englishMonth
    }
    fun getTranslatedCategory(chineseCategory: String): String {
        return CATEGORY_TRANSLATIONS[chineseCategory] ?: chineseCategory
    }
    fun getTranslatedTag(chineseTag: String): String {
        return TAG_TRANSLATIONS[chineseTag] ?: chineseTag
    }
    fun getTranslatedGenre(chineseGenre: String): String {
        return GENRE_TRANSLATIONS[chineseGenre] ?: chineseGenre
    }
    fun getTranslatedSort(chineseSort: String): String {
        return SORT_TRANSLATIONS[chineseSort] ?: chineseSort
    }
    fun getTranslatedYear(chineseYear: String): String {
        return YEAR_TRANSLATIONS[chineseYear] ?: chineseYear
    }
    fun getTranslatedMonth(chineseMonth: String): String {
        return MONTH_TRANSLATIONS[chineseMonth] ?: chineseMonth
    }
    fun getTranslatedTagsForCategory(chineseCategory: String): List<String> {
        return emptyList()
    }
}
